### ISSUE TITLE
Loop (.nocache.nocache...) when sling:include has no path attribute

### ISSUE THREAD

**Issue by mleczey** [wttech/Sling-Dynamic-Include#15]
When `sling:include` did not have `path` attribute ( `<sling:include resourceType="..." />`) dispatcher was asking for parent `/content/application/en/home/page/_jcr_content.nocache.html`, and then for `/content/application/en/home/page/_jcr_content.nocache.nocache.html` and so on (`.nocache.nocache.nocache...`). Result was: page included about ten times (after tenth `.nocache` dispatcher gave up in finding component). There could be a mechanism preventing from multiple `.nocache` with warning/error message notifying about this situation.

**Comment by devzbysiu** [comment]
This project has been moved to https://github.com/apache/sling-org-apache-sling-dynamic-include and it's not maintained here. Closing
