### ISSUE TITLE
Component will be cached if sent request on AEM with /ignoreURLparams

### ISSUE THREAD

**Issue by AbrosimovPavel** [wttech/Sling-Dynamic-Include#22]
If you will use dispatcher setting /ignoreURLparams and sent request on publish with this settings component will be cached because of SSI logic https://github.com/Cognifide/Sling-Dynamic-Include/blob/master/src/main/java/com/cognifide/cq/includefilter/IncludeTagWritingFilter.java#L86
In SSI thats not possible to exclude all URL params and as result component will be cached even use setting to being excluded from cache by selector.

**Comment by AbrosimovPavel** [comment]
Solution suggested - https://github.com/Cognifide/Sling-Dynamic-Include/pull/21

**Comment by devzbysiu** [comment]
This project has been moved to https://github.com/apache/sling-org-apache-sling-dynamic-include and it's not maintained here. Closing
