### ISSUE TITLE
SDI issue - Dynamic component also cached !!!

### ISSUE THREAD

**Issue by roshiniraman** [wttech/Sling-Dynamic-Include#23]
I have integrated SDI in my project. After enabling SDI filter for a component, include tag is being added correctly and the page is also cached. But the issue here is that the component included in SDI is cached as well, Rather, it should fetch during load time.
Could you provide a solution for this issue.

**Comment by davidjgonzalez** [comment]
Can you provide the applicable SDI OSGi config and the dispatcher cache config? 

You need to ensure that the nocache selector is enabled for the SDI include request and that the nocache selector is one your dispatcher cache no-cache rules.

**Comment by devzbysiu** [comment]
This project has been moved to https://github.com/apache/sling-org-apache-sling-dynamic-include and it's not maintained here. Closing
