### ISSUE TITLE
When Dispatcher cache is initially created - The includes are not processed

### ISSUE THREAD

**Issue by henrykuijpers** [wttech/Sling-Dynamic-Include#25]
When caching a page that has SSI tags, for some reason the includes are not processed.

I.e. the page is served with
`<!--#include virtual="/path/to/content/_jcr_content/root/main/some-component.caching-prevented.html" -->`

However, when I then refresh that page, the include *is* processed and the sub-request ends up in AEM.

**Comment by devzbysiu** [comment]
This project has been moved to https://github.com/apache/sling-org-apache-sling-dynamic-include and it's not maintained here. Closing
