### ISSUE TITLE
SDI encoding ESI 

### ISSUE THREAD

**Issue by bertieucbs** [wttech/Sling-Dynamic-Include#26]
We have to append ESI $(GEO{'country_code'} to end of url 

<esi:include src="/master_website/en_US/_jcr_content/hero.nocache.$(GEO{'country_code'}).html"/>

but it is getting encoded like this

hero.nocache.$(GEO%7B'country_code'%7D).html

this is throwing error at the akamai side

How can we avoid this? Since SDI also supports ESI so this should work without issues

Thanks
nitin

**Comment by devzbysiu** [comment]
This project has been moved to https://github.com/apache/sling-org-apache-sling-dynamic-include and it's not maintained here. Closing
