### ISSUE TITLE
IgnoreUrlParams Wildcards in the SlingDynamicInclude Config do not work as expected (AEM 6.4)

### ISSUE THREAD

**Issue by anban02** [wttech/Sling-Dynamic-Include#29]
Hello

i have the following problem in my AEM instance but i think it might be a general problem.

The issue i am facing is that in my dispatcher configuration there are several parameters defined with a * as wildcard.
This is configured for our tracking engine where users might get a link to a page with one of these parameters.

For example:
> https//www.mypage.com/latest-news?testengine-usergroup=10

In this case my dispatcher is configured to ignore the paramers that match the following:
> testengine-*

When i configured this in my SlingDynamicInclude config on the server under the ignoreUrlParams it does not see the above parameter from the url as matching for ignoreUrlParams.

```config
include-filter.config.extension=""
include-filter.config.enabled=B"true"
include-filter.config.path="/content"
include-filter.config.required_header="Server-Agent\=Communique-Dispatcher"
include-filter.config.include-type="SSI"
include-filter.config.selector="nocache"
include-filter.config.add_comment=B"true"
include-filter.config.appendSuffix=B"true"
include-filter.config.rewrite=B"false"
include-filter.config.ttl=""
# These are the urlParams from the dispatcher that are ignored by as such and will load from cache (for tracking etc.)
# If you do not ignore them then a page with rendered SDI will be cached if the call contains these parameters
include-filter.config.ignoreUrlParams=[
    "gclid",
    "testengine-*"
]
include-filter.config.resource-types=[
    "mypage/components/slingdynamic/dynamicbanner"
]
```

Instead the SDI component will completely render and since my dispatcher was configured to ignore this parameter, the response will be cached with an already rendered SDI-Component instead of the SDI-Tag.

I hope this information is enough to understand what my problem is.
If there are some more informations that you need or if something is not clear enough please tell me and i will try to update everything that is needed

**Comment by devzbysiu** [comment]
This project has been moved to https://github.com/apache/sling-org-apache-sling-dynamic-include and it's not maintained here. Closing
